### PR TITLE
first draft of imprint

### PR DESCRIPTION
**Pull request by feststelltaste**

### CODE REVIEW

**Comment by erdlet** [comment]
Seems to be ok as first draft

**Comment by erdlet** [comment]
Is this the imprint and privacy policy in one file?

**Review by erdlet — COMMENTED** [review]
Please check other comment :)

**Review by erdlet — CHANGES_REQUESTED** [review]
Please add a first draft of the pug-Page which contains the imprint so we can link it

**Review by Ebano — APPROVED** [review]
Ok for me as non-jurist :) Thanks, Markus!

**Comment by erdlet** [comment]
Manuell in den new style branch eingebaut

**Pull request closed without merging**
